name = "rtiow"
version = "0.1.0"
license = "license"
author = "Lewis McMillan"
maintainer = "lewismcmillan@gmail.com"
copyright = "Copyright 2021, Lewis McMillan"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
